# Generated by Django 3.2.18 on 2023-10-06 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='创建时间')),
                ('path', models.CharField(db_index=True, max_length=50, verbose_name='uri')),
                ('interface_id', models.CharField(default='', max_length=30, verbose_name='method-接口标识')),
                ('api_type', models.IntegerField(choices=[(0, 'GateWay'), (1, 'restful'), (3, 'other')], default=0, verbose_name='接口类型')),
                ('method', models.IntegerField(choices=[(0, 'POST'), (1, 'GET'), (2, 'DELETE'), (3, 'PUT')], default=0, verbose_name='请求类型')),
                ('content_type', models.IntegerField(choices=[(0, 'application/json'), (1, 'text/html'), (2, 'multipart/form-data'), (3, 'text/plain'), (4, 'application/xml'), (1, 'application/x-www-form-urlencoded')], default=0, verbose_name='请求体类型')),
                ('api_name', models.CharField(max_length=50, verbose_name='接口名称')),
                ('describe', models.CharField(default='', max_length=500, verbose_name='描述')),
                ('version', models.CharField(default='1.0.0', max_length=6, verbose_name='版本')),
                ('state', models.IntegerField(choices=[(0, '服务中'), (1, '已下线'), (3, '已迭代'), (4, '开发中'), (5, '迭代中-新接口并行服务中')], default=0, verbose_name='状态')),
                ('Attentions', models.CharField(default='', max_length=800, verbose_name='注意项')),
                ('note', models.TextField(default='', verbose_name='备注')),
                ('maintainer', models.CharField(default='', max_length=150, verbose_name='维护人')),
                ('is_login', models.BooleanField(default=True, verbose_name='是否需要登录')),
                ('require_auth', models.CharField(default='', max_length=60, verbose_name='权限')),
                ('req_example', models.TextField(default='', verbose_name='请求示例')),
                ('rsp_example', models.TextField(default='', verbose_name='返回示例')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_by', models.CharField(default='', max_length=15, verbose_name='创建人')),
                ('update_by', models.CharField(default='', max_length=15, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '接口',
                'verbose_name_plural': '接口',
                'db_table': 'apis',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='创建时间')),
                ('code', models.CharField(max_length=12, verbose_name='编码')),
                ('name', models.CharField(default='', max_length=30, verbose_name='名称')),
                ('maintainer', models.CharField(default='', max_length=80, verbose_name='维护人')),
                ('note', models.TextField(default='', verbose_name='备注')),
                ('port', models.CharField(max_length=6, verbose_name='端口')),
                ('host', models.CharField(default='127.0.0.1', max_length=18, verbose_name='IP')),
                ('encrypt_mode', models.TextField(default='无', verbose_name='加密方式')),
                ('sign_mode', models.TextField(default='无', verbose_name='签名方式')),
                ('create_by', models.CharField(default='', max_length=15, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='创建时间')),
                ('path', models.CharField(db_index=True, max_length=50, verbose_name='uri')),
                ('interface_id', models.CharField(default='', max_length=30, verbose_name='method-接口标识')),
                ('api_type', models.IntegerField(choices=[(0, 'GateWay'), (1, 'restful'), (3, 'other')], default=0, verbose_name='接口类型')),
                ('method', models.IntegerField(choices=[(0, 'POST'), (1, 'GET'), (2, 'DELETE'), (3, 'PUT')], default=0, verbose_name='请求类型')),
                ('content_type', models.IntegerField(choices=[(0, 'application/json'), (1, 'text/html'), (2, 'multipart/form-data'), (3, 'text/plain'), (4, 'application/xml'), (1, 'application/x-www-form-urlencoded')], default=0, verbose_name='请求体类型')),
                ('req', models.TextField(default='', verbose_name='请求示例')),
                ('rsp', models.TextField(default='', verbose_name='返回示例')),
            ],
            options={
                'verbose_name': '接口库表',
                'verbose_name_plural': '接口库表',
                'db_table': 'request_logs',
            },
        ),
        migrations.CreateModel(
            name='Params',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='创建时间')),
                ('code', models.CharField(max_length=30, verbose_name='参数代码')),
                ('name', models.CharField(max_length=50, verbose_name='参数名称')),
                ('param_type', models.IntegerField(choices=[(0, 'str'), (1, 'integer'), (2, 'boolean'), (3, 'datetime'), (4, 'array'), (5, 'object')], default=0, verbose_name='参数类型')),
                ('is_require', models.BooleanField(default=False, verbose_name='是否必传')),
                ('is_null', models.BooleanField(default=True, verbose_name='是否可为空')),
                ('example', models.CharField(default='', max_length=30, verbose_name='示例')),
                ('note', models.CharField(default='', max_length=300, verbose_name='备注')),
                ('is_service', models.BooleanField(db_index=True, default=True, verbose_name='是否服务中')),
                ('create_by', models.CharField(default='', max_length=15, verbose_name='创建人')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.api', verbose_name='所属接口')),
            ],
            options={
                'verbose_name': '参数',
                'verbose_name_plural': '参数',
                'db_table': 'params',
            },
        ),
        migrations.AddField(
            model_name='api',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.project', verbose_name='所属项目'),
        ),
    ]
