# Generated by Django 3.2.18 on 2023-10-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_requestlog_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='content_type',
            field=models.IntegerField(choices=[(0, 'application/json'), (1, 'text/html'), (2, 'multipart/form-data'), (3, 'text/plain'), (4, 'application/xml'), (5, 'application/x-www-form-urlencoded')], default=0, verbose_name='请求体类型'),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='content_type',
            field=models.CharField(default='', max_length=30, verbose_name='请求体类型'),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='method',
            field=models.CharField(default='', max_length=8, verbose_name='请求类型'),
        ),
    ]
