# Generated by Django 3.2.18 on 2023-10-09 18:44

from django.db import migrations
import mirage.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20231008_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='note',
            field=mirage.fields.EncryptedTextField(default='', verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='api',
            name='req_example',
            field=mirage.fields.EncryptedTextField(default='', verbose_name='请求示例'),
        ),
        migrations.AlterField(
            model_name='api',
            name='rsp_example',
            field=mirage.fields.EncryptedTextField(default='', verbose_name='返回示例'),
        ),
        migrations.AlterField(
            model_name='project',
            name='encrypt_mode',
            field=mirage.fields.EncryptedTextField(default='无', verbose_name='加密方式'),
        ),
        migrations.AlterField(
            model_name='project',
            name='note',
            field=mirage.fields.EncryptedTextField(default='', verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sign_mode',
            field=mirage.fields.EncryptedTextField(default='无', verbose_name='签名方式'),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='err',
            field=mirage.fields.EncryptedTextField(default='', verbose_name='异常信息'),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='req',
            field=mirage.fields.EncryptedTextField(default='', verbose_name='请求示例'),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='rsp',
            field=mirage.fields.EncryptedTextField(default='', verbose_name='返回示例'),
        ),
    ]
