# Generated by Django 3.2.18 on 2023-10-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20231009_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='content_type',
            field=models.CharField(default='', max_length=38, verbose_name='请求体类型'),
        ),
    ]
