# Generated by Django 3.2.18 on 2023-11-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20231104_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='params',
            name='own_type',
            field=models.CharField(default='request', max_length=10, verbose_name='所属类型'),
        ),
    ]
