# Generated by Django 3.2.18 on 2023-11-05 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_params_own_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='interface_id',
            new_name='api_method',
        ),
    ]
