# Generated by Django 3.2.18 on 2024-02-23 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_interface_id_api_api_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.api', verbose_name='原始接口'),
        ),
        migrations.AlterField(
            model_name='api',
            name='state',
            field=models.IntegerField(choices=[(0, '开发中'), (2, '服务中'), (1, '已下线'), (3, '已迭代'), (4, '迭代中'), (5, '迭代中-新旧接口并行服务中')], default=0, verbose_name='状态'),
        ),
    ]
