# Generated by Django 3.2.18 on 2024-02-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20240223_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='params',
            name='example',
            field=models.CharField(default='', max_length=500, verbose_name='示例'),
        ),
    ]
