# Generated by Django 3.2.18 on 2024-05-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_params_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='headers',
            field=models.TextField(blank=True, default='', null=True, verbose_name='请求头'),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='headers',
            field=models.TextField(blank=True, default='', null=True, verbose_name='请求头'),
        ),
    ]
