# Generated by Django 3.2.18 on 2024-05-17 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_auto_20240515_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_created=True, verbose_name='创建时间')),
                ('userId', models.IntegerField(db_index=True, verbose_name='用户ID')),
                ('projectId', models.BigIntegerField(db_index=True, verbose_name='项目ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('is_read', models.BooleanField(default=True, verbose_name='是否已读')),
            ],
            options={
                'verbose_name': '关注列表',
                'verbose_name_plural': '关注列表',
                'db_table': 'notices',
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, verbose_name='创建时间')),
                ('projectId', models.BigIntegerField(db_index=True, verbose_name='项目ID')),
                ('apiId', models.BigIntegerField(db_index=True, verbose_name='接口ID')),
                ('api_name', models.CharField(default='', max_length=50, verbose_name='接口名称')),
                ('api_describe', models.CharField(default='', max_length=500, verbose_name='描述')),
                ('content', models.CharField(default='', max_length=300, verbose_name='内容简述')),
                ('by', models.CharField(default='', max_length=200, verbose_name='发布人')),
            ],
            options={
                'verbose_name': '发布历史表',
                'verbose_name_plural': '发布历史表',
                'db_table': 'releases',
            },
        ),
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='创建时间')),
                ('config', models.JSONField(verbose_name='配置内容')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户配置表',
                'verbose_name_plural': '用户配置表',
                'db_table': 'user_configs',
            },
        ),
    ]
