# Generated by Django 3.2.18 on 2024-05-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_release_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='project_name',
            field=models.CharField(default='', max_length=30, verbose_name='名称'),
        ),
    ]
